name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies & test
        run: 
        - npm install
        - npm run start
        - npx percy snapshot snapshots.yml