name: Tests
build:
  runs-on: ubuntu-latest
  - uses: actions/checkout@v2
    - name: Install dependencies & test
      run: 
      - npm install
      - npm run start
      - npx percy snapshot snapshots.yml
    