name: My Workflow
on:
  push:
    branches:
      - 'main'
env:
  message: 'conversation'
  my_token: ${{ secrets.GITHUB_TOKEN }}
jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
      - name: Say something
        run:
          - npm install
          - npm run start
          - npx percy snapshot snapshots.yml